### ISSUE TITLE
MAJCOM Summary Report Modification

### ISSUE THREAD

**Issue by tleonard6** [CHAD-Analytics/CHAD#1]
- [x]  Add a column for cumulative cases for each installation (quick add)

- [x]  Add a third csv download that has the same information as the installation csv, but specific to the actual/single county where the base is located

**Comment by galarcon0308** [comment]
On the first one, we can change hospital bed column to cumulative cases when "cases" is selected on the sidebar

**Comment by tleonard6** [comment]
Sorry, I did this awhile ago and forgot to close.  When selecting cases, I added the Total case column.  The cases datatable is one column larger than the hospitalizations datatable.
