### ISSUE TITLE
Add filter for MAJCOM summary report

### ISSUE THREAD

**Issue by ajkeith** [CHAD-Analytics/CHAD#11]
**Is your feature request related to a problem? Please describe.**
Need additional filter label for Majcom summary for 16AF. This might be an issue since bases will have a dual label between traditional majcom and 16AF. Might need a separate column label in the dataframe stating 16AF or not. This is necessary for the overseas bases

**Additional context**
Issue ported from old repo.

**Comment by Auburngrads** [comment]
Is this different from #2 ?

**Comment by ajkeith** [comment]
@Auburngrads I think you're right, I'll close this one
