### ISSUE TITLE
Add additional models to hurricane projection

### ISSUE THREAD

**Issue by ajkeith** [CHAD-Analytics/CHAD#12]
**Is your feature request related to a problem? Please describe.**
Add a wider variety of models. 

**Describe alternatives you've considered**
Currently adding in Columbia University Model and Los Alamos National Laboratory Models. Should be ready to push very soon.

**Additional context**
Issue ported from old repo.

@tleonard6: @galarcon0308 This is done and pushed, now includes 4 models and multiple scenarios. The only thing left is find a better fix for downloading the LANL data.

@galarcon0308: Nice! Yeah I was testing it last night. Found a bug locally where if you press the select all button on the sidebar by the model check boxes, the app crashes and closes. Not sure what is causing it yet.

@tleonard6: It's something to do with the session. When I ran it locally it wouldn't work unless I included session. But now it crashes

**Comment by ajkeith** [comment]
Thanks to great work by @tleonard6 and @galarcon0308 this is live at https://covid19dash.shinyapps.io/CHAD-Test/

**Comment by tleonard6** [comment]
Still looking at a couple additional models to add very soon.

**Comment by ajkeith** [comment]
Wow awesome.

**Comment by tleonard6** [comment]
Leaving this open. Added University of Texas model projections.  Looking at several others.
