### ISSUE TITLE
Add detailed county info

### ISSUE THREAD

**Issue by ajkeith** [CHAD-Analytics/CHAD#13]
Items 1-3 are immediate items, 4 is additional when there is time
1.  Add in  1, 3, 5, 7 and 14 day case increase rates.
Rationale/Intent:  provides better picture of the trend (trending up or trending down)
2.  Add in weekly rate of change in case count (graph of how the growth in cases is changing over time).
Rationale/Intent:  Would like to see if the speed of the case increase is slowing down over time
3.  Add in current number of recovered cases on current local health tab.  

4.  Consider a projection of the number recovered based on the average recovery time 
-       A case is "active" on average of 14-days ... so then add daily new case counts for 14 days and subtract from cumulative and deaths
Rationale/intent:  this is an estimate but can eventually help us assess the level of immunity in the community

**Additional context**
Issue ported from old repo. 

@galarcon0308: Just looking for some clarification on this one. Is this going in the county table on the Current Local Health tab?

@tleonard6: @galarcon0308 yes, 1-3, #4 is a possibility for the projection tab

**Comment by mattburzenski** [comment]
Any interest in using a 3 day rolling average for the daily case counts? That's what the CDC uses and it looks a lot cleaner and less noisy than CHAD's current daily case count graph.

**Comment by galarcon0308** [comment]
Yeah I've been thinking about this for a minute. The inconsistent reporting creates lots of unnecessary noise. I think a 3 day average would be good or a weekly growth average. I we may still need to have the daily chart there solely because I anticipate people requesting the continued need to see daily reported case numbers. 

One thing that might show more and save space is to create a tabbed box. So the box the daily chart is in will instead have two tabs, one for daily chart and one for 3-day average. Users could flip between the two to get the visual of the smoothing function but still see actual case numbers by day. 

Maybe?

**Comment by ajkeith** [comment]
@jeff-henderson @tleonard6 are these the SG asks?

**Comment by tleonard6** [comment]
@ajkeith This is the closest SG ask 

Current Local Health Tab:  Add a Weekly rate of change in case count (graph of how the growth in cases is changing over time).

Weekly rate of change in case count (graph of how the growth in cases is changing over time).

Rationale/Intent:  Would like to see if the speed of the case increase is slowing down over time

**Comment by mattburzenski** [comment]
![image](https://user-images.githubusercontent.com/63305329/80619468-bc373300-8a12-11ea-825c-72efc8240936.png)
Hey guys, let me know what you think of the draft plot above. The data points are 3 day moving averages for case count. The growth rate is calculated by comparing the moving average of the last 7 days to the moving average of the last 14 days. >10% change is high growth, -10% - 10% is stable, <-10% is negative growth (word smithing needed).

**Comment by tleonard6** [comment]
@mattburzenski I think this is really good.  I believe that it captures what they're looking for

**Comment by galarcon0308** [comment]
Most of these items have been incorporated.
