### ISSUE TITLE
Installations in large counties don't properly display data/projections

### ISSUE THREAD

**Issue by ajkeith** [CHAD-Analytics/CHAD#14]
**Describe the bug**
When the installation is located in a large county, the standard 50 mile radius does not always include the county in which the installation exists.  This leads to inaccurate current local health data/local health projections

**To Reproduce**
See Edwards or DM.  Current local health projections are inaccurate/incomplete until the user scales out far enough to "catch" the county center.

**Expected behavior**
When an installation is selected it should include the county in which it exists regardless of the installations proximity to the county's centroid or the user defined radius.

**Screenshots**
![image](https://user-images.githubusercontent.com/26749415/80229183-0e94e000-861e-11ea-9c26-aa177392c7d3.png)

**Additional context**
Ported from old issues.

@galarcon0308: Tracking on this sir, thanks for submitting it. Didn't realize it was bugging out the local projections also. We might have a fix to roll out by tomorrow night. By editing the AFBaselocation.csv to have the county it belongs to (FIPS Code). Then filter based on counties in the radius AND including the home county.

@galarcon0308: Quick fix has been provided, using the method mentioned above. Will keep open until a full fix is done. At the moment, no matter how low the radius, the closest county will still be captured at a minimum. A full fix would require a comb through of the AFBaselocations.csv to ensure each base has it's proper home county.

**Comment by galarcon0308** [comment]
Issue has been fixed since master base sheet was created.
