### ISSUE TITLE
Add overseas locations

### ISSUE THREAD

**Issue by ajkeith** [CHAD-Analytics/CHAD#15]
**Is your feature request related to a problem? Please describe.**
Urgent need to include Overseas locations ASAP

**Additional context**
Issue ported from old repo.

**Comment by galarcon0308** [comment]
Overseas data running on test server for current local health tab and national summary. Still need map visualization for bases but not a high priority. Will close when projection models get integrated.

**Comment by tleonard6** [comment]
Closing.  OCONUS projections are in progress, will be completed soon
