### ISSUE TITLE
Extend projection period beyond 30 days

### ISSUE THREAD

**Issue by ajkeith** [CHAD-Analytics/CHAD#18]
**Describe the solution you'd like**
"A9 decided to limit the forecasting timeline to reduce the difference from what we actually expect to see, but I think that kind of hides the issue.  Our approach is to present the CHAD forecast as “potential outbreak” rather than a prediction of what is to come.  With that being said, we would like to be able  to project past 30 days to see the “potential” peak in the hospitalizations" from Mr. McKelvey via email on 22 Apr. @himey97, please feel free to elaborate on the concerns.

**Comment by ajkeith** [comment]
The projections previously showed low uncertainty far into the future where the single-peaked models generally project low hospitalizations and deaths. However, we know that the single-peaked models we have are a subset of possible futures and that there are credible models with a much larger range of uncertainty out into the future. Even the multi-peak and trigger-based mitigation models understate uncertainty far in the future because of unknowns about policy and disease progression.

Given that this tool will be used by non-analysts it's important that we avoid showing users projections that look highly certain when they are not.

I know that this is a controversial topic, so I'd like to open the floor for discussion in this issue.

**Comment by tleonard6** [comment]
@ajkeith I think once we begin to include multi-peak and/or trigger based models we should have a separate slider/selection for that plot that extends 30/60/90/120 days to see the potential fluctuations.

**Comment by ajkeith** [comment]
@tleonard6 I think that's reasonable. 

In the AFAC meeting today Dr. Giddings also suggested the possibility of letting certain customers (SG, A9s) have the ability to extend the timeframe as well. Not sure how we would go about implementing that but I see the utility.

**Comment by tleonard6** [comment]
@ajkeith Having customized access would be great, but not sure about implementation.  If we get our own server, we could in theory have multiple CHAD instances instead...

**Comment by ajkeith** [comment]
Have not received further input on this suggestion and the current behavior is in-line with DoD and the interagency. I'll close this until it comes up again.
