### ISSUE TITLE
Improve the utility of the display

### ISSUE THREAD

**Issue by ajkeith** [CHAD-Analytics/CHAD#19]
**Is your feature request related to a problem? Please describe.**
"I’ll reiterate the limited / no utility of the display.  Having that customizable would be helpful" from Mr. McKelvey via email on 22 Apr.

**Describe the solution you'd like**
@himey97 can you provide more details on the additional features desired for the display?

**Comment by Auburngrads** [comment]
What exactly does this mean? In Mr. McKelvey's opinion what would provide utility?

**Comment by himey97** [comment]
I'm not sure this really should have been logged as an issue.   We have a requirement to build slides for the COMACC CAT briefing.   We're leveraging the CHAD tool as much as possible.  In the slide building process we "enhance" the pictures and fonts to make them more presentable. The comment was meant to communicate the CHAD tool presents it's results in one way graphically that you accept as is and cannot user modify. Attached in an example of what our guys do on the left is ACC, on the right is CHAD.  Recommend closing issue.
![NellisCapture](https://user-images.githubusercontent.com/25903556/80375202-e5ff2700-8865-11ea-8087-9c284ef8fee7.JPG)

**Comment by ajkeith** [comment]
If you'd like to change the plot labels to reduce the manual work of relabeling, I think there wouldn't be any disagreement. The plotting functions are at https://github.com/CHAD-Analytics/CHAD/blob/master/covid19/www/4_load_functions/PlotOverlay.R and https://github.com/CHAD-Analytics/CHAD/blob/master/covid19/www/4_load_functions/PlotOverlay2.R.

On your recommendation, I'll close the issue, but please feel free to update the figure labeling if you'd like and let us know if there are any roadblocks.
