### ISSUE TITLE
Ability to select and deselect counties in Current Local Health

### ISSUE THREAD

**Issue by weirj1** [CHAD-Analytics/CHAD#20]
Dr Giddings indicated the ability to add or delete counties from the Local health would be useful for leaders to determine what counties to include vice just a radius.

I will look at this, perhaps grayed out ares not being included (out to 100) miles and then color them if selected.

**Comment by weirj1** [comment]
This has been completed.  I have pushed my code to the branch called plotClick.  I am not that familiar with GIt Hub., what else do I need to do?

**Comment by weirj1** [comment]
okay, plan B need to go back and redo work based on new version of CHAD.  More to follow.

**Comment by tleonard6** [comment]
@weirj1 would you mind checking the current code to see if it’s working properly?

**Comment by weirj1** [comment]
Is it in the master?

**Comment by tleonard6** [comment]
Yes, master should have everyone’s edits

**Comment by weirj1** [comment]
Ok ill take a look tomorrow

**Comment by weirj1** [comment]
The counties are displaying correctly in version 0.9.5 (published) but can't select.  Looked at Master ad all the code is commented out.  Tomorrow I will look at the code and get it working on the current master and let you know.

**Comment by weirj1** [comment]
fix pushed to selectCounties branch
