### ISSUE TITLE
Dynamic Sidebar

### ISSUE THREAD

**Issue by weirj1** [CHAD-Analytics/CHAD#21]
The side bar is very busy and not clear what to use when.  A dynamic sidebar might make it easier to use.

**Describe alternatives you've considered**

See this dynamic sidebar version of CHAD.

https://covid19dash.shinyapps.io/DynamicSidebar/

**Comment by tleonard6** [comment]
@weirj1 This is great, please push to master when you have the chance.

**Comment by weirj1** [comment]
Pushed
