### ISSUE TITLE
Documentation for AMC projection

### ISSUE THREAD

**Issue by acady14** [CHAD-Analytics/CHAD#22]
we have some documentation that we'd like to add in to the AMC projection section -- what is the best way to do so?  we can either give a short markdown file that gives you the highlights or a PDF of a longer report.

**Comment by ajkeith** [comment]
I think the fastest way to update would be updating/replacing the markdown at https://github.com/CHAD-Analytics/CHAD/blob/master/covid19/www/6_load_info_docs/AMC_Desc.md

**Comment by galarcon0308** [comment]
I'll echo what @ajkeith said. Probably a short markdown with the highlights. Feel free to edit the markdown posted above. That file controls what is seen next to the chart on the tab. The longer report would still be necessary if you all have it, and we can put it in a folder on github and link to it in the markdown or in the *More Information* section

**Comment by acady14** [comment]
could you add me as a contributor so I can make a new branch with the modified .md file?

**Comment by acady14** [comment]
thanks!

**Comment by tleonard6** [comment]
Just sent you an invite

**Comment by acady14** [comment]
I'm still having issues with permissions -- I've attached the updated file below if one of you guys wants to add it in and make the commit.  Not sure why, but it is still giving me a 403 error when I try to push the new branch.  (change file extension to .md)
[AMC_Desc.txt](https://github.com/CHAD-Analytics/CHAD/files/4541542/AMC_Desc.txt)

**Comment by galarcon0308** [comment]
No worries, I got you.
