### ISSUE TITLE
Columbia University date download issue

### ISSUE THREAD

**Issue by tleonard6** [CHAD-Analytics/CHAD#24]
The current setup for downloading Columbia University data where it checks the date was functioning properly unless the recorded date was backdated enough. Right now the date is hard coded for the most recent file date.  Maybe there's a way around this...maybe not.  If we need to change it manually regularly, we can.

**Comment by Auburngrads** [comment]
Created a new branch `columbia_data_dynamic_path` that contains a new function `get.shaman.lab.path()`.  The function web-scrapes the shaman-lab repo folders and identifies the 'Projection_XXX' folder with the most recent date in the title.

<h1>🚨 THE BIGGER ISSUE 🚨</h1> 
I had to rearrange the steps that were performed in global.R 🙅 because <b><u>the functions should be loaded after the packages are loaded and before the data is ingested</u></b>.  If this causes confusion think about this: I created a function to help load the data, but as previous constructed the app functions were loaded AFTER the data was ingested. 
<br/><br/>
Take a look at the function and let me know what you think.  May want to wait until a more recent folder is uploaded to the shaman-lab repo to test before merging.

**Comment by tleonard6** [comment]
@Auburngrads That all makes sense and I took the new arrangement and have been using it on my personal branch.  Everything works great.  Still one issue, whenever I try to deploy to my test app I get the following error on R Shiny

![image](https://user-images.githubusercontent.com/29178867/80756650-ecf59600-8b00-11ea-9285-32b53dc94cb8.png)

So it's something related to the LANL import.  The weird thing is, everything runs great on my personal computer.  Is there a reason why it shouldn't work in the deployment?  This is the LANL code I'm using.

#'  Get data from Los Alamos National Lab
#' @param front front of url
#' @param middle middle of url
#' @param end end of url 
#' @param date Have to adjust the integer value based on the date of the most recent forecast file
#' @export
#' @importFrom vroom vroom
#' 
get_lanl_data <- function(){
  
  R.utils::downloadFile("https://covid-19.bsvgateway.org/forecast/forecast_metadata.json",
                        filename = "www/4_load_external_data/data_files/forecast_metadata.json",
                        overwrite = T)
  
  bsv_metadata<-jsonlite::fromJSON("www/4_load_external_data/data_files/forecast_metadata.json")
  Front<-'https://covid-19.bsvgateway.org/forecast/us/files/'
  Middle1<-'/confirmed/'
  Middle2<-'/deaths/'  
  End1<-'_confirmed_quantiles_us_website.csv'
  End2<-'_deaths_quantiles_us_website.csv'  
  Date<-bsv_metadata$us$most_recent_date

  LANL_file_name1<-paste0(Front,Date,Middle1,Date,End1)
  LANL_file_name2<-paste0(Front,Date,Middle2,Date,End2)

  LANLC_Data<-vroom::vroom(LANL_file_name1)
  LANLD_Data<-vroom::vroom(LANL_file_name2)
  
  LANLC_Data<-subset(LANLC_Data, 
                    select = -c(simple_state,q.01,q.025,q.05,q.10,q.15,q.20,q.30,q.35,q.40,q.45,q.55,q.60,q.65,q.70,q.80,q.85,q.90,q.95,q.975,q.99,truth_confirmed,fcst_date))
  LANLD_Data<-subset(LANLD_Data, 
                     select = -c(simple_state,q.01,q.025,q.05,q.10,q.15,q.20,q.30,q.35,q.40,q.45,q.55,q.60,q.65,q.70,q.80,q.85,q.90,q.95,q.975,q.99,truth_deaths,fcst_date))
  
  LANLC_Data <- merge(LANLC_Data, 
                     StateList, 
                     by.x = names(LANLC_Data)[6], 
                     by.y = names(StateList)[1])
  
  LANLD_Data <- merge(LANLD_Data, 
                     StateList, 
                     by.x = names(LANLD_Data)[6], 
                     by.y = names(StateList)[1])
  
  names(LANLC_Data)[names(LANLC_Data)=="state.abb"] <- "State"
  names(LANLD_Data)[names(LANLD_Data)=="state.abb"] <- "State"
  
return(list(LANLC_Data,LANLD_Data))

}

**Comment by Auburngrads** [comment]
Is this function defined on your personal branch?  

Have you tried restarting R on your machine to verify that you don't have an object named `LANL_file_name1` floating around that gives you a false positive when it works locally?

**Comment by tleonard6** [comment]
I was able to figure it out.  Restarting helped me trace it.  Thank you
