### ISSUE TITLE
COVID Testing Priority

### ISSUE THREAD

**Issue by mattburzenski** [CHAD-Analytics/CHAD#25]
Hey y'all, I noticed COVID Testing is high on the CHAD development priorities (Tier 1). Is anybody currently working this? 

I'm pretty familiar with COVID testing data and am happy to help out however possible.

**Comment by galarcon0308** [comment]
Yeah we def want to get this in. Currently looking (for both CHAD versions) adding a ratio of tests administered to confirmed cases. Installations are starting to think of a multiplier that indicates that their local region is doing enough tests, which is looking to be 100:1 (so 100 tests per confirmed case). The site we get the global data also has a sheet with the total test. Just need to calculate and extract those ratios, and slap them on the current local health tab for each installation. 

GitHub for the data : https://github.com/open-covid-19/data

Actual data: https://open-covid-19.github.io/data/v2/latest/master.csv

**Comment by galarcon0308** [comment]
This has been incorporated, separate issue exist with the JHU data and changing file names. Need a better way to pull it.
