### ISSUE TITLE
Display RIVAL as a new tab

### ISSUE THREAD

**Issue by ajkeith** [CHAD-Analytics/CHAD#28]
**Describe the solution you'd like**
Develop a new tab for Lt Col Crivellaro's risk vulnerability tool (RIVAL) as a separate tab. 

**Describe alternatives you've considered**
We've discussed hosting RIVAL next to ORM but the consensus was that RIVAL fits better with the CHAD collection of tools.

An intermediate option is to link to or display a pdf. 

**Additional context**
Current RIVAL is available on APAN or via SAFE (it's large).

**Comment by tleonard6** [comment]
@ajkeith are we allowed to integrate on the Public site?

**Comment by ajkeith** [comment]
as far as I understand, the current version is all open source

**Comment by JCCriv76** [comment]
RIVAL is open source and the PDF it outputs (manually) is small. The RIVAL excel workbook is 40+ MBs.

**Comment by tleonard6** [comment]
@JCCriv76 I don't think it's overly difficult to set RIVAL up as a tab and automate it.  Would you be able to draw a rough flow chart of what excel tab you start on and flow through to get to your final export table?

**Comment by courtneylknoth** [comment]
I'm currently working this issue.

**Comment by JCCriv76** [comment]
Courtney, let me know if you still need a flow chart and/or if you'd like to chat about RIVAL.

**Comment by courtneylknoth** [comment]
Lt Col Crivellaro - I have a copy of your spreadsheet and white paper.  Right now I have a blank tab in CHAD for RIVAL.  What information would you like on the tab?  Perhaps we can have a conversation tomorrow to discuss.

**Comment by JCCriv76** [comment]
I'm available all day tomorrow. Do you want to meet on MS Teams?  Send me an invite with the time and we'll discuss. Thanks for taking this on!

**Comment by courtneylknoth** [comment]
I just set up a MS Teams meeting at 1300 with you and Maj Leonard.  Feel free to invite others

**Comment by JCCriv76** [comment]
Great! I've uploaded an updated excel file to APAN. The first three sheets of the workbook are what should be shown within a CHAD tab (USAFR & Active Duty, ANG, and Core Missions). I also added a 14-Day Trajectory column to depict each installation's progress towards meeting WH reopening guidelines (it's only for reference, it's not calculated within the dataset).

**Comment by courtneylknoth** [comment]
Thanks, I'll take a look.  Also, I'm pushing the meeting to 1400.  Let me know if that is a problem for you.

**Comment by courtneylknoth** [comment]
I just logged on to APAN and don't have any files in the COVID folder.  I was able to get the spreadsheet from Taylor though.  Did you make recent updates?

**Comment by galarcon0308** [comment]
Closing this for now as this is on hold. Can be reopened later.
