### ISSUE TITLE
Add Confidence Interval to Estimated Bed Capacity 

### ISSUE THREAD

**Issue by jeff-henderson** [CHAD-Analytics/CHAD#3]
**Is your feature request related to a problem? Please describe.**
Recommend adding a confidence interval to the Estimated Covid Patient Bed Capacity red line within the Local Health Projections tab.  Displaying a shaded confidence interval region would make it more clear to users that this is an estimate.  This seems to be an area of interest for analysts and non-technical users alike.

**Describe the solution you'd like**
Add shaded confidence interval.  Up to you guys on what that should be statistically.

**Describe alternatives you've considered**
There was once an issue to have that line removed; however, it is extremely useful, we just need to make it a little more obvious what it is.  Additionally, if near real-time hospitalization data become available we could eventually use that (seems highly unlikely and no-one across the DoD-Inter-agency has that figured out yet)

**Comment by ajkeith** [comment]
I think this would help address comments we received from Mr. McKelvey on 22 Apr: "The hospitalization data is not accurate and only a calculated estimation (e.g. assumes certain percentage of non-COVID patients)" @himey97, please let us know if this doesn't address the problem.

**Comment by galarcon0308** [comment]
Having the estimated capacity from Torch gives a solution to this. Two lines now
