### ISSUE TITLE
SG Requests

### ISSUE THREAD

**Issue by tleonard6** [CHAD-Analytics/CHAD#31]
Current open SG requests

- [x]   Current Local Health Tab, Local County Statistics:  Add 1, 3, 5, 7 and 14 day case increase rates

Request: 1, 3, 5, 7 and 14 day case increase rates.
Rationale/Intent:  provides better picture of the trend (trending up or trending down)
 

- [x]  Current Local Health Tab:  Add a Weekly rate of change in case count (graph of how the growth in cases is changing over time).

Weekly rate of change in case count (graph of how the growth in cases is changing over time).
Rationale/Intent:  Would like to see if the speed of the case increase is slowing down over time

- [x]  Current Local Health Tab, Total Report Chart:   Add recovered line

Request:  Track Number recovered by county (or an estimate of the number recovered)
Source:  pending a good source of this information, but could use a formula 
-A case is "active" on average of 14-days ... so then add daily new case counts for 14 days and subtract from cumulative and deaths
Rationale/intent:  this is an estimate but can eventually help us assess the level of immunity in the community

**Comment by galarcon0308** [comment]
This has been completed.

**Comment by galarcon0308** [comment]
Thinking about this more, #2 I don't think adds much value. If the goal is to see speed of case increase/decrease over time, that I believe is being accomplished by the daily case chart, and smoothed out to look better with the daily chart using 3-day moving averages. This gives you velocity of cases. The 14-day one I made doesn't illuminate much so I can going to remove it. If I do a weekly one (based on weekly totals) i don't if that gives anymore than the single day over time. It will be larger numbers (cases for total week), so an aggregated version of the daily chart. 

I can use percentages but then it's kind of strange to explain how each day's percent growth is based on the previous day (or week). I feel that chart could be misrepresented. Most people tend to have a hard time understanding a chart of acceleration (which would be the speed of case growth). 

Let me know what you think. I could probably be missing something, or thinking incorrectly. Maybe there is a better way to display this? Maybe just a single most recent weekly (or daily) change in case growth.

Here is an example of the daily case growth rate as a raw number (ignore the x-axis label, should be daily)
![image](https://user-images.githubusercontent.com/52179539/81362773-a3341f00-90af-11ea-97e9-41b6e2c8f926.png)


And as a percent
![image](https://user-images.githubusercontent.com/52179539/81363548-99132000-90b1-11ea-95da-8980aa85faab.png)

**Comment by galarcon0308** [comment]
I added a chart based on weekly case counts every Monday, starting when an area has over 30 total cases. Hopefully to filter out the starting 4000% increases.
