### ISSUE TITLE
IHME Data Download issue

### ISSUE THREAD

**Issue by tleonard6** [CHAD-Analytics/CHAD#33]
IHME added a dated folder and an extra csv file to their zipfile.  Need to modify the vroom function to account for the folder and extra file.

**Comment by levilott** [comment]
Hey guys this might help. I just tried it and it works on my end. Pulls the most recent IHME Projected data.

#Store URL for most recent IHME Zip File
url <-"https://ihmecovid19storage.blob.core.windows.net/latest/ihme-covid19.zip"

#Create 2 temp files
temp <- tempfile()
temp2 <- tempfile()

#Download the zip file and unzip
download.file(url, temp)
unzip(zipfile = temp, exdir = temp2)

#Defnie path up to the latest date
IHME_Path <- list.files(path = temp2, full.names = TRUE)
#Ammend path with desired file name
#Using Projected data here but could also use "Summary_stats_all_locs.csv" if you wanted that info
IHME_Path <- paste(IHME_Path, "/Hospitalization_all_locs.csv", sep = "")
#Stores the data
IHME_data <- read.csv(IHME_Path)
#Unlinks the temp files
unlink(c(temp, temp2))

**Comment by tleonard6** [comment]
This worked great!  Thank you!
