### ISSUE TITLE
Operational Status dropdown "All" not populating

### ISSUE THREAD

**Issue by ajkeith** [CHAD-Analytics/CHAD#38]
**Describe the bug**
Current Local Health Base Selector dropdown:   ALL does not populate,  must select AD, Guard, or Res

**Additional context**
Posted by @himey97 in mm.

**Comment by tleonard6** [comment]
@himey97 We removed "All" because it was effecting the other drop downs.  If we can get it to work smoothly, we'll put it back up, if not, then it will have to stay out.
