### ISSUE TITLE
National Summary Charts should have color slider label.

### ISSUE THREAD

**Issue by dominic-babbini** [CHAD-Analytics/CHAD#39]
The map chart on the National Summary tab has a color coded slider but the numbers there are not explained. The slider should have a text label stating the meaning. It seems to be an arbitrary relative scale based on new confirmed cases. This could either be labeled as relative scale of new cases or rescaled to the actual number of cases.

Scale depicted below:
![image](https://user-images.githubusercontent.com/65415604/82239925-8a293a80-9907-11ea-8680-d1bb148afc4a.png)

**Comment by galarcon0308** [comment]
Slider has been hid for the moment until we can figure out in the gvis package how to control the legend. Plot color is based off a log scale to show a more dynamic range and not be controlled by outliers like NY. Unfortunately it then displays with the log scale on the legend.

**Comment by galarcon0308** [comment]
This will require a change in mapping packages. This is not being pursued at the moment. If the situation changes, I'll reopen and change the mapping package.
