### ISSUE TITLE
Add a legend to the MAJCOM summary map

### ISSUE THREAD

**Issue by ajkeith** [CHAD-Analytics/CHAD#4]
**Is your feature request related to a problem? Please describe.**
Mr. Swallow requested we add a legend that explains the size of the dot in addition to the color (which currently displays only when there are red & green dots together). Can we make the legend display unconditionally and add the description of what the size of the dot represents?

**Additional context**
Discussion from old issue:
Spencer Butt: Is the intent with this chart to only show the IHME estimate? If this is the case we don't need to use size and color. We can just use color to show the IHME estimate of the Projected Daily New Cases.
With only color we'll add a color scale in the legend.

Trey Pujats: There is a radio button to change between IHME and CHIME estimates. We use color to show whether the number of hospitalizations is greater than the number of available beds based on historical hospital bed utilizations. We have the color of the legend included, and we are adding a legend for bubble size which shows the number of cases/hospitalizations.

**Comment by ajkeith** [comment]
@courtneylknoth can I assign this issue for you for after #7?

**Comment by courtneylknoth** [comment]
Working this issue now!

**Comment by ajkeith** [comment]
Re @courtneylknoth: changing to ggplot would be okay but losing the interactivity would be less than ideal. There are so many dots that the interactivity helps for checking individual installations without labeling all of them. @Sleekery do you have any ideas on how to fix these legends for plotly (I'm pretty sure it should have the same capabilities as python plotly, it should just be a different R command for it)?

**Comment by Sleekery** [comment]
I've barely used plotly, but it isn't easy to make a size scale legend? I imagine you can have a second legend showing size. If it's difficult to create a proper legend, what I do on matplotlib create new dots off screen and have them be the points creating the legend.

**Comment by courtneylknoth** [comment]
I'm asking Dominic about this question right now since he has experience with plotly R from C3RAF.

**Comment by courtneylknoth** [comment]
With Dominic's help, we got the colors fixed.  Still working the sizes

**Comment by courtneylknoth** [comment]
The colors and sizes are working.  What do you think of this?
![image](https://user-images.githubusercontent.com/22075623/80752037-de0ae580-8af8-11ea-9e7c-6bb7d09aa687.png)

**Comment by ajkeith** [comment]
That looks great!
