### ISSUE TITLE
Local Health Projections Tab Not Populating

### ISSUE THREAD

**Issue by dominic-babbini** [CHAD-Analytics/CHAD#40]
The Local Health Projections tab is not populating the graphs. It has intermittently populated but often displays this error:
Error: An error has occurred. Check your logs or contact the app author for clarification.

**Comment by galarcon0308** [comment]
There is issue with some of the overseas locations. Error checking is being put in to at least not show the error message and display something else. If you come across any CONUS locations that have an issue, feel free to update this issue with the base and models selected, and we can look at those particularly. Thanks!

Currently I know **JB Anacostia** has an issue.
