### ISSUE TITLE
National Summary tab-COVID-19 Health Assessment Dashboard Beta v0.9.7

### ISSUE THREAD

**Issue by jane-stoner** [CHAD-Analytics/CHAD#41]
National Summary tab - map
- [x] Go to the state of Georgia in the US and hover.  It shows 701 cases.  If you go to the table below and look at GA, it shows 34,006 (data is as 1730, 18 May 2020).  I think it is somehow linking to the country of Georgia and not the US state of Georgia.
- [x] Is there a way that when you pick US that you only see US state data rather than the world?  Europe, the same thing?
- [x] One last thing - is there a way to freeze the title of the columns in the table, so you can still see them when you scroll through all the data?

Let me know if I need to separate these issues.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 79.0.3945.117

Thanks,
Jane Stoner
HQ AFRC/A9
DSN 497-2242
jane.stoner@us.af.mil

**Comment by galarcon0308** [comment]
Thanks for the feedback! We can keep this all in one issue. I will just post here when each piece is complete.

**Comment by ajkeith** [comment]
@jane-stoner thanks for including such specific details in your issue! That helps a lot!

**Comment by galarcon0308** [comment]
The column header freezing is being a little more trickier than I thought but the other parts have been updated and are present in the main version

**Comment by jane-stoner** [comment]
No worries about header freezing - just a nice to have.  Thanks for the other 2!  ajkeith-glad I could help!

**Comment by ajkeith** [comment]
Removed bug label since the last remaining checklist item is an enhancement.

**Comment by galarcon0308** [comment]
Instead of a fixed header, we reduced the table size to 15 per page. And the user can click through table pages instead of scrolling through the long list.

**Comment by jane-stoner** [comment]
Thanks!  I’m sure that will work!

 

Jane W. Stoner

Operations Research Analyst

HQ AFRC/A9A

Robins AFB, GA

 <mailto:jane.stoner@us.af.mil> jane.stoner@us.af.mil

 <mailto:jane.w.stoner.civ@mail.smil.mil> jane.w.stoner.civ@mail.smil.mil

Comm: 478-327-2242

DSN 312-497-2242

Cell Phone:  478-952-5176
