### ISSUE TITLE
Incorrect Coordinates/Counties for Installations

### ISSUE THREAD

**Issue by tleonard6** [CHAD-Analytics/CHAD#43]
- [x]  Eglin AFB is pulling the wrong counties.  Either there is a wrong lat/long or wrong installation county

- [x]  MCAS Miramar, under marine corps, active duty.  location says san francisco, should be san diego

- [x]  AF Plant 42, wrong lat/long, correct county

**Comment by galarcon0308** [comment]
Changed to check marking completed ones.
