### ISSUE TITLE
Tab 2 Feature Requests

### ISSUE THREAD

**Issue by tleonard6** [CHAD-Analytics/CHAD#45]
On Tab 2

1.  Change the scale to cases/100,000 instead of cases
2.  Look into if we can display multiple values when hovering over country/region

**Comment by galarcon0308** [comment]
This for just the county plot? or for the value box also that says cases per 1000. Can def display multiple values on hovering tooltip using plotly. Which things were you thinking?

**Comment by tleonard6** [comment]
By Tab 3, I meant tab 2, hopefully that makes more sense

**Comment by galarcon0308** [comment]
Completed
