### ISSUE TITLE
Minot data anomaly 

### ISSUE THREAD

**Issue by novaktroy** [CHAD-Analytics/CHAD#49]
**Describe the bug**
MINOT AFB DATA IS INCORRECT DO TO A CHANGE IN STATE FIGURES
**To Reproduce**
1. Go to '...' "CURRENT LOCAL HEALTH"
2. Click on '....' "SELECT MINOT AFB
3. Scroll down to '....' "DAILY NEW CASES CHART"
4. See error "SEE SPIKE on ~5/19/2020"

**Additional context**
THE STATE CHANGED THE REPORTED NUMBERS AND THIS APP IS USING OLD DATA

**Comment by galarcon0308** [comment]
Thanks for alerting us to this. All of our data is sourced from JHU as referenced in the sources section. We will look into if they have done any updates or are tracking on the state reporting changes. They were very responsive when NYC changed their reporting and had a one day spike also.

**Comment by galarcon0308** [comment]
JHU and USAFacts still seem to be showing the spike, albeit in perspective it isn't a large spike. We will continue relying on JHU data and leave the fixes to them, but keep note of the anomaly. Thanks again!
