### ISSUE TITLE
MAJCOM summary hotspot chart filter 

### ISSUE THREAD

**Issue by ajkeith** [CHAD-Analytics/CHAD#5]
**Describe the bug**
Bug exists when sidebar MAJCOM filter selects any of the below bases, hot spot chart throws an error or displays no bases. This might be due to the way the cases are being counted, or filters placed on the chart.

AFSOC
PACAF
UASFA
HQ

**Additional context**
Issue ported from old repo.

**Comment by ajkeith** [comment]
@SpencerButt I assigned to you based on your comment in the old repo

**Comment by galarcon0308** [comment]
This has been fixed. Issue involved division by 0 in certain instances.
