### ISSUE TITLE
Automate LANL Date

### ISSUE THREAD

**Issue by levilott** [CHAD-Analytics/CHAD#53]
Good evening Maj Leonard,

Apologies as I'm still getting the hang of navigating github and this could probably be a pull request rather than an issue but I did not understand how to create an appropriate pull request. 

I'd like to offer the code at the bottom of this message that could automatically pull the most recent Date for LANL updates rather than it being explicitly defined.

Please let me know if I can provide any additional information or if I should be placing these items in another location.

Thanks sir!

Your original code (shortened to just show pieces relevant to Date): 

R.utils::downloadFile("https://covid-19.bsvgateway.org/forecast/forecast_metadata.json",
                        filename = "www/4_load_external_data/data_files/forecast_metadata.json",
                        overwrite = T)
  
  bsv_metadata<-jsonlite::fromJSON("www/4_load_external_data/data_files/forecast_metadata.json")

  Date<- "2020-06-17" #bsv_metadata$us$most_recent_date
 
My proposed update:

#Store metadata link
URL_metadata <- "https://covid-19.bsvgateway.org/forecast/forecast_metadata.json"

#Create temp file
temp <- tempfile()

#Download the json file and store in temp
download.file(URL_metadata, temp)

#pull the json attributes
LANL_metadata <- fromJSON(temp)

unlink(temp)

Date <- LANL_metadata$us$most_recent_date

**Comment by galarcon0308** [comment]
I'll give this a try tonight and throw it in. Thanks for looking at this! Pulling those pesky files with changing file names was always an annoyance to us. Much appreciated!

**Comment by tleonard6** [comment]
@levilott you're a rockstar
