### ISSUE TITLE
Production Instance Down

### ISSUE THREAD

**Issue by SeanMaday** [CHAD-Analytics/CHAD#58]
It appears the production instance is down:
https://afit.shinyapps.io/covid19/

**Comment by tleonard6** [comment]
Hi Sean, thank you, will have it resolved this evening

**Comment by galarcon0308** [comment]
It is up and running now. An intermittent server issue occurred. We'll keep this issue open for a couple days in case it happens again, and we need to address. Thanks for bringing it to our attention!

**Comment by SeanMaday** [comment]
Confirmed! It is working from my end. Thank you!
