### ISSUE TITLE
MAJCOM summary hotspot axis scaling

### ISSUE THREAD

**Issue by ajkeith** [CHAD-Analytics/CHAD#6]
**Is your feature request related to a problem? Please describe.**
Hot Spot chart on MAJCOM Summary tab needs fixed axis on the y-scale along with fixed scaling bounds on the bubble size and color. This is so when the filter for MAJCOM is changed, a large red bubble will correspond to the scale among all bases as opposed to just among the filtered bases. Allows for proper visual comparison when filter is changed.

**Additional context**
Ported from old repo.

**Comment by mattburzenski** [comment]
working this now

**Comment by ajkeith** [comment]
@courtneylknoth, I think you were looking at this too?

**Comment by courtneylknoth** [comment]
Yes - I was and I just gave the fix to Matt to incorporate with some of his other updates.

**Comment by mattburzenski** [comment]
![image](https://user-images.githubusercontent.com/63305329/80415249-427f3800-88a0-11ea-9ffa-c85025675506.png)

Reworked the presentation a bit (legend on the bottom so the width isn't shrunken) and fixed the y-axis, color, and size to all be absolute scaling instead of R's default relative scaling. 

I haven't tried merging to the repo, but I did work this code using Maj Freels' new code structure so it should be relatively easy to merge with his existing code.

**Comment by mattburzenski** [comment]
The CDC is using a week-by-week comparison for their growth rate, which might be easier to digest than this chart. Essentially for the CDC chart, if the point is above the x-axis there have been more cases in the last week than there were in the previous week, and "negative growth" if the point is below the x-axis. 

I already have the code implemented in R to make those calculations, so if we want to change the chart slightly to be more standardized with the CDC and also easier to follow, let me know.

**Comment by galarcon0308** [comment]
Awesome! Yeah I think if you can, we should change to the week by week look that the CDC is using. That's in line also with the national summary tab which has average cases on a weekly average. Nice job @courtneylknoth and @mattburzenski !

**Comment by mattburzenski** [comment]
![image](https://user-images.githubusercontent.com/63305329/80487733-4310e080-892b-11ea-8f87-9550bed0f182.png)

**Comment by mattburzenski** [comment]
Here's what the chart for weekly % change in cases looks like. 

I know Dr Giddings was looking to somehow label the graph so it made it easier for the user to digest. She recommended a shaded region for high/low growth areas. Maybe I could do a blue shading below 0% growth and red shading above 50,75, or 100% growth? With a really low alpha value so it doesn't make the points hard to distinguish

**Comment by ajkeith** [comment]
@mattburzenski looking good! Can we be a little more explicit with the deaths label? I think it's Cumulative Deaths right?

The shading sounds good too

**Comment by mattburzenski** [comment]
The region shading is proving more difficult than expected...

**Comment by ajkeith** [comment]
Okay let's skip it and get the 80% solution pushed up to the branch
