### ISSUE TITLE
Getting started/info tab

### ISSUE THREAD

**Issue by ajkeith** [CHAD-Analytics/CHAD#7]
**Is your feature request related to a problem? Please describe.**
Need a design mockup/idea for possible construction of a new tab. The new tab would be the first tab seen when the app loads up. The tab could contain overview information, how to get started, and links to further documentation (could be Github write ups).

**Additional context**
Ported from old repo.

**Comment by Auburngrads** [comment]
Another option could be to use the `rintrojs` package as a way to introduce the features of the app

Check the demo [**here**](https://introjs.com/)

**Comment by courtneylknoth** [comment]
I agree, rintrojs looks like a great way to make a first tab with overview information, etc.

**Comment by courtneylknoth** [comment]
Everything in www/6_load_info_docs should be on the tab as a minimum

**Comment by ajkeith** [comment]
@courtneylknoth it sounds like you're working this so I went ahead and assigned it you (feel free to change if needed)

**Comment by Auburngrads** [comment]
Not sure that another tab is needed.

rintrojs creates an overlay that highlights features of the app so that you don't need a dedicated tabPanel that contains this information.

Neither option is better, just two layout choices

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by courtneylknoth** [comment]
I'm working to move the 'More Information' tab right before the MAJCOM Summary tab.  I like the way it's currently organized and feel that it will be better noticed at this location.  Thoughts?

**Comment by Auburngrads** [comment]
Sure that's great.

It definitely puts the info about the app right up front. Probably need to have the "front page" organized by tabs so the viewer understands what they'll see when they go there.

The big issue with this layout choice is making sure that the front page is kept current with all subsequent *viewer facing* app changes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by courtneylknoth** [comment]
![image](https://user-images.githubusercontent.com/22075623/80824140-d5271c00-8bab-11ea-8ab8-5c49800ad51d.png)

**Comment by galarcon0308** [comment]
It took awhile for us to get to this but thanks @courtneylknoth for providing the foundation code for this! Was able to adapt it, and implement very easily.
