### ISSUE TITLE
Integrate AMC model

### ISSUE THREAD

**Issue by ajkeith** [CHAD-Analytics/CHAD#9]
**Is your feature request related to a problem? Please describe.**
Integrate AMC SIR Infection model into overlay plots. Parse out cumulative deaths, cumulative infections, and daily infections. Estimate hospitalization burden from infection number and hospitalization rates

**Additional context**
Issue ported from old repo.

Alarcon: It's been copied into the server on line 294-372 called output$ProjectedEpidemicTable

It has been integrated onto a new tab, and currently working. Next would be to parse out the individual pieces of data and add them to the overlay. Or at least add them as a test and let's see how it looks.

**Comment by galarcon0308** [comment]
Non-FOUO version added
